version: 0.1
phases:
  install:
    commands:
      - cd function && pip install -r requirements.txt -t .
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket ${LAMBDA_ARTIFACTS_BUCKET} --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
